### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by RobbieTheWagner** [bekzod/ember-animatable#1]
I'm not seeing any animations on Ember-CLI 2.6

**Comment by bekzod** [comment]
what is specifically not working I am in ember-cli 2.6.1 and it is working perfectly, maybe you can paste some could to show how you are using it ?

**Comment by RobbieTheWagner** [comment]
Hi @bekzod, yeah, I can definitely get you an example. No animations were happening for me at all, and I tried both the mixin and the standard import way. Not sure if something with liquid fire was stopping it from working, or if I need to `@import` some styles if I am using ember-cli-sass or something?

**Comment by bekzod** [comment]
Hi, example of how you are using it would help, it does not need anything to do from you, it imports css files so there no need for sass or less libs.

**Comment by RobbieTheWagner** [comment]
@bekzod I know with several other addons, like ember paper, if you are using sass, you have to import the styles or they don't get pulled in. If you are using plain css, it is automatic though. It may be the same case here.

**Comment by RobbieTheWagner** [comment]
@bekzod you can see my attempt at usage here https://github.com/shipshapecode/website/blob/master/app/components/technologies-section/component.js

**Comment by bekzod** [comment]
@rwwagner90 have you checked if it is actually triggered ? have you put console.log or debugger within `didEnterViewport`, have you tried putting it within `click(){}` and checking if it animates when clicked on component

**Comment by RobbieTheWagner** [comment]
@bekzod I am positive the `didEnterViewport` hook is called. I tried putting it in `didInsertElement` as well, which is definitely called every time, and still no animations.

**Comment by RobbieTheWagner** [comment]
@bekzod do you think you could take a look at my repo and see if you can determine why it does not work?

**Comment by bekzod** [comment]
sure, is it open source  ?

**Comment by RobbieTheWagner** [comment]
@bekzod yeah, I sent you the link to the code previously

**Comment by RobbieTheWagner** [comment]
@bekzod still not able to make this work. I see the classes applied to the elements, but no animations. Perhaps the actual animate.css is not being added in?

**Comment by bekzod** [comment]
released new version you could try it, also tried new version works, so closing this

**Comment by RobbieTheWagner** [comment]
I think it just doesn't include the CSS, so animations don't happen, even though classes are applied. Are you manually importing the CSS in your test cases?

**Comment by bekzod** [comment]
They are imported, if you open vendor.css you should see .animated classes
